# Generated by Django 4.0.5 on 2022-06-30 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='venue',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='venue_image',
            new_name='location_image',
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=120, verbose_name='Event Name'),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=120, verbose_name='Location Name'),
        ),
    ]
